### ISSUE TITLE
Server crashes after the first batch of Laravel Logs

### ISSUE THREAD

**Issue by cpave3** [cpave3/nlog#1]
# Error

```
/Users/cameron/Development/nlog/node_modules/nosqlite/lib/nosqlite.js:47
          if (data[k] === cond[k]) {
                  ^

TypeError: Cannot read property 'id' of undefined
    at /Users/cameron/Development/nlog/node_modules/nosqlite/lib/nosqlite.js:47:19
    at Array.every (<anonymous>)
    at Object.satisfy (/Users/cameron/Development/nlog/node_modules/nosqlite/lib/nosqlite.js:46:34)
    at /Users/cameron/Development/nlog/node_modules/nosqlite/lib/nosqlite.js:159:27
    at ReadFileContext.callback (/Users/cameron/Development/nlog/node_modules/nosqlite/lib/nosqlite.js:89:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)
```

**Comment by cpave3** [comment]
This will probably be fixed by #2 anyway
